name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.2
      - name: Create coverage files
        run: deno test --coverage=coverage # create coverage files
      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov # create coverage report
      - name: Collect coverage
        uses: codecov/codecov-action@v1.0.10 # upload the report on Codecov
        with:
          file: ./coverage.lcov